URL:
    LOGINPAGE: http://www.zhihu.com/#signin
    LOGIN: http://www.zhihu.com/login
    QUESTIONS: http://www.zhihu.com/log/questions
    HOME: http://www.zhihu.com
    CAPTCHA-PREFIX: http://www.zhihu.com

HEADERS:
    INIT:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Encoding: gzip,deflate
        Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2
        Connection: keep-alive
        Host: www.zhihu.com
        Referer: http://www.zhihu.com/log/recent
        User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.114 Safari/537.36

    MOD:
        Referer: http://www.zhihu.com/log/questions
        X-Requested-With: XMLHttpRequest

VALIDATE:
    EMAIL: 你的邮箱
    PASSWORD: 你的密码

DB:
    FILE: db.txt

NODES:
    CAPTCHA: //img[@class='js-captcha-img']
    TEST: //a[@id='top-nav-dd-topic']
    PAGE: //div[@class='zm-item']
    JSON: /html/body/div
    TITLE: ./h2[@class='zm-item-title']/a
    WHO: ./div/a
    TIME: .//time

EXCEPTIONS: exceptions.txt
